### ISSUE TITLE
Bulk CreateReducer and CreateEffects

### ISSUE THREAD

**Issue by stevehalliwell** [ActuatorDigital/Fluxity#34]
## Describe the task

Presently you write a bind for each reducer and each effect. This works fine but results in a lot of lines, often all referencing methods of the same class/object. This is also easy to forget to add and become confused as to why that new reducer didn't fire.

## Additional context

In an internal project we have:
- 23 lines of CreateReducer for 5 features, 5 pure static reducer classes,
- 50ish lines of CreateEffect for 15ish Effect classes.

**Comment by Strowy** [comment]
Simple change for Effects would be to move the binding (currently CreateEffect in the Initializer) into the effect class, and add a pattern method that is then called for the class from the Initializer which does all the binding.

Effect of this change:
- Only one line in the initializer
- When more bindings are added to the effect class, only that class needs changing, does not need to touch the initializer
- Class knowledge doesn't change, as only the Dispatcher is needed for Effect binding, and Effects already need to know about the Dispatcher

**Comment by stevehalliwell** [comment]
source generators would be the path forward here I think https://medium.com/@EnescanBektas/using-source-generators-in-the-unity-game-engine-140ff0cd0dc but feels like potentially a lot of investment effort

**Comment by Strowy** [comment]
Superseded by Reducer / Effect registration changes.
